#!/bin/bash

args=$#; min=0; max=0; resolv_t=0; itr=0

setup(){
	case $args in
	# set the resolve time value to user input, and set the iterations to default 1
	1)
		resolv_t=$1
		itr=1;
		;;
	# set the interval from where the kanji is chosen
	2)
		min=$1
		max=$2
		resolv_t=3
		itr=1;
		;;
	# set the interval from where the kanji is chosen, when the resolve time value is also set 
	3)
		min=$2
		max=$3
		resolv_t=$1
		itr=1;
		;;
	# set the interval from where the kanji is chosen and the resolve time value, when the iterations number is also set 
	4)
		min=$2
		max=$3
		resolv_t=$1
		itr=$4
		;;
	# set resolve time to a default 3sec value and the iterations to 1, if no value is specified
	*)
		resolv_t=3
		itr=1;
	esac
}

get_Kanji(){
	# set the interval of from where the kanji is chosen 
	case $args in
	2)
		val=$(./randomHeisigKeyword $min $max); echo $val; sleep $resolv_t; val=$(grep -o '[0-9]*' <<< "$val"); ./randomHeisigKanji $val
		;;
	3)
		val=$(./randomHeisigKeyword $min $max); echo $val; sleep $resolv_t; val=$(grep -o '[0-9]*' <<< "$val"); ./randomHeisigKanji $val
		;;
	4)
		val=$(./randomHeisigKeyword $min $max); echo $val; sleep $resolv_t; val=$(grep -o '[0-9]*' <<< "$val"); ./randomHeisigKanji $val
		;;
	*)
		val=$(./randomHeisigKeyword); echo $val; sleep $resolv_t; val=$(grep -o '[0-9]*' <<< "$val"); ./randomHeisigKanji $val
		;;
	esac
}

check_arguments(){
	if [ $args -gt 4 ]; then
		echo "Numeber of arguments must not exceed 4 !!, "
		echo "Please run once more with either of the following syntaxes:\n"
		echo "./randomHeisigK\&K\n"
		echo "./randomHeisigK\&K \$timer\n"
		echo "./randomHeisigK\&K \$smallest_kanji_number \$largest_kanji_number\n"
		echo "./randomHeisigK\&K \$timer \$smallest_kanji_number \$largest_kanji_number \$iterations\n"
		exit
	fi
}

####################################  MAIN  ####################################

check_arguments
setup $1 $2 $3 $4
while [ $itr -gt 0 ]; do
	itr=$((--itr))
	get_Kanji
done
