#!/bin/bash

if [ $# -eq 2 ]
then
	MIN=$1;
	MAX=$2;
else
	MIN=1;
	MAX=2042;
	NUM=$1;
fi


RANGE=$(($MAX-$MIN+1));
RESULT=$RANDOM
let "RESULT %= $RANGE";
RESULT=$(($RESULT+$MIN));

if [ $# -eq 1 ]
then
	cat heisig-data.txt | grep -o "^${NUM}:.";
else
	cat heisig-data.txt | grep -o "^${RESULT}:.";
fi
